### ISSUE TITLE
TypeError while running imdb_demo.py

### ISSUE THREAD

**Issue by bhavyaarora** [swilly22/redis-graph#96]
- python3 imdb_demo.py
```
port=None, path=/usr/local/bin/redis-server, loadmodule=/home/bhavya/redis-graph/src/redisgraph.so
Loading movies
Loaded 283 movies
Loading actors
Loaded 1318 actors
Traceback (most recent call last):
  File "imdb_demo.py", line 53, in <module>
    main(sys.argv[1:])
  File "imdb_demo.py", line 48, in main
    imdb_utils.populate_graph(redis_con, redis_graph)
  File "/home/bhavya/redis-graph/demo/imdb/imdb_utils.py", line 61, in populate_graph
    redis_graph.commit()
  File "/home/bhavya/redis-graph/demo/social/venv/lib/python3.5/site-packages/redisgraph/client.py", line 126, in commit
    return self.query(query)
  File "/home/bhavya/redis-graph/demo/social/venv/lib/python3.5/site-packages/redisgraph/client.py", line 135, in query
    result_set = [res.split(',') for res in data]
  File "/home/bhavya/redis-graph/demo/social/venv/lib/python3.5/site-packages/redisgraph/client.py", line 135, in <listcomp>
    result_set = [res.split(',') for res in data]
TypeError: a bytes-like object is required, not 'str'
```

**Comment by swilly22** [comment]
@bhavyaarora 
Thank you for bringing this to my attention, this is an issue within redisgraph-py which uses redis-py,
From redis-py readme:

"By default, all responses are returned as bytes in Python 3 and str in Python 2. The user is responsible for decoding to Python 3 strings or Python 2 unicode objects.
If all string responses from a client should be decoded, the user can specify decode_responses=True to StrictRedis.__init__. In this case, any Redis command that returns a string type will be decoded with the encoding specified."

I'll push a fix shortly.
